# Local PostgreSQL database
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/auth_db
spring.datasource.username=user
spring.datasource.password=password

# Validate the schema created by Flyway and log SQL while developing.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

# Jwt configuration
jwt.secret-key=super-secret
jwt.expiration-time=1800