# Local PostgreSQL database
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/auth_db
spring.datasource.username=user
spring.datasource.password=password

# Validate the schema created by Flyway and log SQL while developing.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

# Jwt configuration
jwt.secret-key=fa813022b4a69ec35a51bbcc8af2efd3524a2e8a53395f9d4a892875d8d71c26
jwt.expiration-time=1800