# Local PostgreSQL database
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/auth_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true