# Local development settings
storage.location=./uploads

# Local PostgreSQL database
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/storage_db
spring.datasource.username=user
spring.datasource.password=password

# Validate the schema created by Flyway and log SQL while developing.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
